## Docker Compose for Forgejo
## Based on https://forgejo.org/docs/latest/admin/installation-docker/#docker

networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:9
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
    volumes:
      ## Mount the Forgejo Volume for Docker, because macOS Rancher Desktop doesn't allow setting ownership for Local Filesystem
      - forgejo-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      ## Web Server will be exposed at HTTP Port 3002
      - '3002:3000'
      - '222:22'

## Define the Forgejo Volume for Docker
volumes:
  forgejo-data:
